default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: localhost

development:
  <<: *default
  database: simple_blog_development

test:
  <<: *default
  database: simple_blog_test

production:
  <<: *default
  database: simple_blog_production
  username: simple_blog
  password: <%= ENV['SIMPLE_BLOG_DATABASE_PASSWORD'] %>
